### ISSUE TITLE
Wide resnet adopted here is different from the official one ??

### ISSUE THREAD

**Issue by YBZh** [google-research/fixmatch#31]
Good work and thanks for your code.

I have one question that the wide resent adopted here seems different from the official one, besides the number of the filter ?? I believe the following codes give the implementation of the wide resnet, right? 
https://github.com/google-research/fixmatch/blob/b41d9e3744768986eef24176c98e6f01bef401ee/libml/models.py#L62

For example, the dropout is adopted in each block and the Relu activation is adopted in the official one, while the Dropout is only adopted before the final FC layer and the LeakyRelu activation is adopted here ??

**Comment by carlini** [comment]
Yes, there are differences between our WRN and other implementations. Minor differences like this are the big reason that Oliver et al. (2018) state "different algorithms must be evaluated using the same model to avoid conflating comparison". Because all methods we compare to use this same model, we can be sure that it is the improved method---and not just a different model---that causes the accuracy gains.

**Comment by YBZh** [comment]
I get it. Thanks for your reply.

**Comment by Chen-Song** [comment]
But actually the dropout parameter is set to 0 in the actual running of the code, right?
