### ISSUE TITLE
How to include all labeled examples as part of unlabeled data?

### ISSUE THREAD

**Issue by happygds** [google-research/fixmatch#53]
The FixMatch paper said that "In practice, we include all labeled examples as part of unlabeled data without using their labels when constructing U". I'm curious about how to include all labeled examples as part of unlabeled data. 

Did you repeat the labeled examples or just concatenate them with the unlabeled data? 

In semi-supervised learning, if you just use 1% samples of ImageNet as labeled data and concatenate them with the remaining 99% samples as unlabeled data, would it really affect the final results?

**Comment by carlini** [comment]
In our dataset creation scrips, we just initialize the unlabeled dataset to be all of the images that we have. The labeled images are then subsetted from the unlabeled dataset.

The reason this is important isn't that we get to add a few percent more images to the unlabeled images, but because the unlabeled images have much stronger augmentations applied. So an image being in the unlabeled dataset means that it sees strong augmentation, whereas if it wasn't then it would only see weak augmentation.

**Comment by happygds** [comment]
From what I understand, if I apply strong augmentation to labeled images for training one-hot classification loss, then there would not exist much differences.

**Comment by carlini** [comment]
It wouldn't quite be completely identical because the labeled examples appear much more frequently in minibatch updates than the unlabeled examples. It may end up working out---it would be interesting to see---but it's not mathematically identical.
